### ISSUE TITLE
mega program

### ISSUE THREAD

**Issue by hypereg** [negative-zer0/HeightCalculatorTool#1]
zawsze marzyłem żeby poprzez aplikacje sprawdzić ile mam wzrostu ale czy można dodać taką opcje jak sprawdzanie swojej wagi ?

**Comment by negative-zer0** [comment]
When I have time I'll add it.

**Comment by negative-zer0** [comment]
[https://github.com/negative-zer0/HeightCalculatorTool/commit/90626d1b684c31f686261e81da8da38b1fcc2a66](url)
